"""
Comet Opik client wrapper for logging guardian interactions.
"""
import os
import logging
from typing import Optional
from datetime import datetime

from models import ConversationMessage, ClassificationVerdict


logger = logging.getLogger(__name__)

# Initialize Opik client (will be done lazily)
_opik_client = None


def _get_opik_client():
    """
    Lazy initialization of Opik client.

    Returns:
        Opik client instance or None if initialization fails
    """
    global _opik_client

    if _opik_client is not None:
        return _opik_client

    try:
        import opik
        from opik import Opik

        api_key = os.getenv("OPIK_API_KEY")
        project_name = os.getenv("OPIK_PROJECT_NAME", "coaching-guardian")
        workspace_name = os.getenv("OPIK_WORKSPACE_NAME")

        if not api_key:
            logger.warning("OPIK_API_KEY not set, logging will be disabled")
            return None

        # Configure Opik
        opik.configure(api_key=api_key, workspace=workspace_name)

        # Initialize client
        _opik_client = Opik(project_name=project_name)
        logger.info(f"Opik client initialized for project: {project_name}")

        return _opik_client

    except ImportError:
        logger.error("opik package not installed. Run: pip install opik")
        return None
    except Exception as e:
        logger.error(f"Failed to initialize Opik client: {e}")
        return None


def log_interaction_to_opik(
    conversation_history: list[ConversationMessage],
    coach_response: str,
    verdict: ClassificationVerdict,
    metadata: Optional[dict] = None,
) -> None:
    """
    Log a guardian interaction to Comet Opik.

    Args:
        conversation_history: List of conversation messages
        coach_response: The response generated by the coaching agent
        verdict: The classification verdict from Friendli
        metadata: Optional additional metadata to log
    """
    client = _get_opik_client()

    if client is None:
        logger.warning("Opik client not available, skipping logging")
        return

    try:
        # Prepare input data
        input_data = {
            "conversation_history": [msg.to_dict() for msg in conversation_history],
            "latest_user_message": (
                conversation_history[-1].content
                if conversation_history and conversation_history[-1].role == "user"
                else ""
            ),
        }

        # Prepare output data
        output_data = {
            "coach_response": coach_response,
        }

        # Prepare tags and metadata
        tags = [
            f"severity:{verdict.severity}",
            "guardian:enabled",
        ]

        if verdict.is_toxic:
            tags.append("toxic:true")
        if verdict.is_sensitive:
            tags.append("sensitive:true")
        if verdict.is_off_topic:
            tags.append("off_topic:true")

        for category in verdict.categories:
            tags.append(f"category:{category}")

        # Combine metadata
        combined_metadata = {
            "guardian_enabled": True,
            "scorer_model_name": os.getenv("FRIENDLI_MODEL_NAME", "meta-llama-3.1-8b-instruct"),
            "timestamp": datetime.utcnow().isoformat(),
            "classification": verdict.to_dict(),
            **(metadata or {}),
        }

        # Log to Opik as a trace
        client.trace(
            name="guardian_interaction",
            input=input_data,
            output=output_data,
            tags=tags,
            metadata=combined_metadata,
        )

        logger.info(f"Logged interaction to Opik with tags: {tags}")

    except Exception as e:
        logger.error(f"Failed to log to Opik: {e}")
        # Don't raise - logging failures shouldn't break the main flow


def log_feedback_to_opik(
    trace_id: str,
    feedback_type: str,
    feedback_value: any,
) -> None:
    """
    Log feedback for a specific trace (optional, for future use).

    Args:
        trace_id: The ID of the trace to attach feedback to
        feedback_type: Type of feedback (e.g., "user_rating", "flagged")
        feedback_value: The feedback value
    """
    client = _get_opik_client()

    if client is None:
        logger.warning("Opik client not available, skipping feedback logging")
        return

    try:
        # This is a placeholder - actual implementation depends on Opik's feedback API
        logger.info(f"Feedback logged for trace {trace_id}: {feedback_type}={feedback_value}")
    except Exception as e:
        logger.error(f"Failed to log feedback to Opik: {e}")
